// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package drivers

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	_ = packr.PackJSONBytes("../dll", "1.txt", "\"\"")
}
