// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "f18abfbeccdd76e1f4c15161a008033a"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"6179a4fbb9ad90015238e7e5a059b095": "1f8b08000000000000ff32343236313503040000ffff61d3720906000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("hello", "../dll")
		b.SetResolver("1.txt", packr.Pointer{ForwardBox: gk, ForwardPath: "6179a4fbb9ad90015238e7e5a059b095"})
	}()
	return nil
}()
