# This is a basic workflow that is manually triggered
#https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
name: deploylikehmi

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # push操作
  push:
    #    branches:
    #      - '**'
    #      - main
    #      - 'releases/**'
    tags:
      - v*.**
  #手动
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
env:
  DAY_OF_WEEK: Monday

  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  WindowsBuild:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      #      - uses: msys2/setup-msys2@v2
      #        with:
      #          update: true
      - name: Build for windows
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        run: |
          go build -o ./build/HelloWorld_Windows_${{ github.ref_name }}.exe ./main.go
      - name: Build for ubuntu
        if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
        run: |
          go build -o ./build/HelloWorld_Linux_${{ github.ref_name }} ./main.go
      #      - name: Upload Artifact
      #        uses: actions/upload-artifact@v2
      #        with:
      #          name: rush_dist
      #          path: "./build/**"
      #          retention-days: 5
      #          if-no-files-found: error
      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "./build/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



