name: webhook
on:
  repository_dispatch:
    types: [ "*event_type*" ]
jobs:

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo My name is P3TERX.
          echo Hello World!
          echo "Hello ${{ toJSON(github) }}"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Hello World2
        run: |
          echo My name is P3TERX. >> ./build1/hello.txt
          echo Hello World! > ./build1/hello.txt
          echo "Hello ${{ github.event}}" > ./build1/hello.txt

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "./build1/**"
          tag_name: ${{ github.event.client_payload.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}